apiVersion: v1
kind: PersistentVolume
metadata:
  name: localvolume-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localvolume-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-localvolume
spec:
  containers:
  - name: container
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
    - name: pod-volumes-localvolume-volume
      mountPath: /etc/data
  volumes:
  - name: pod-volumes-localvolume-volume
    persistentVolumeClaim:
      claimName: localvolume-pvc