load '../../config.rb'

def workerIP(num)
  return "192.168.56.#{num+150}"
end

image = "sbeliakou/centos"

Vagrant.configure("2") do |config|
    # config.vm.provision "Basic OS Provisioning", type: "shell", 
    #     inline: "bash #{scripts_dir}/base.sh"

    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../../", "/vagrant", 
        owner: "vagrant", 
        group: "vagrant"

    (0..$worker_count).each do |index|
        node_name = (index == 0) ? "k8s-master" : "k8s-worker-%d" % index

        config.vm.define node_name do |node|
            node.vm.box = image
            node.vm.hostname = node_name
            node.vm.network :private_network, ip: workerIP(index)

            node.vm.provider :virtualbox do |vb|
                vb.name = node_name
                vb.memory = (index == 0) ? $master_memory : $worker_memory
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                vb.customize ["modifyvm", :id, "--cpuexecutioncap", "#{70/($worker_count+1)}"]
            end

            node.vm.provision "shell", 
                env: {
                    "NODE_TYPE"           => "#{(index == 0) ? 'master' : 'worker'}",
                    "NODE_INDEX"          => "#{index}",
                    "K8S_TOKEN"           => "#{$token}",
                    "WORKER_COUNT"        => "#{$worker_count}",
                    "MASTER_IP"           => "#{workerIP(0)}",
                    "DEPLOY_INGRESS_CTRL" => "#{$ingress_controller}",
                    "DEPLOY_GRAFANA"      => "#{$grafana}",
                    "DEPLOY_PROMETHEUS"   => "#{$prometheus}",
                    "DOMAIN_NAME"         => "#{$domain}",
                    "SCRIPTS_DIR"         => "/vagrant/vagrant/CentOS/scripts/",
                    "CONFIGS_DIR"         => "/vagrant/configs/"
                },
                inline: <<-SHELL
                    /bin/bash ${SCRIPTS_DIR}/base.sh
                    /bin/bash ${SCRIPTS_DIR}/k8s-${NODE_TYPE}.sh ${MASTER_IP} ${K8S_TOKEN}
                    
                    if [ ${NODE_INDEX} -eq ${WORKER_COUNT} ]; then
                        if [ ${WORKER_COUNT} -eq 0 ]; then
                            /bin/bash ${SCRIPTS_DIR}/k8s-master-isolation.sh
                        fi
                        
                        /bin/bash ${SCRIPTS_DIR}/k8s-dashboard.sh

                        if [ "${DEPLOY_INGRESS_CTRL}" == "true" ]; then
                            /bin/bash ${SCRIPTS_DIR}/k8s-ingress.sh ${MASTER_IP} 
                        fi

                        if [ "${DEPLOY_GRAFANA}" == "true" ]; then
                            /bin/bash ${SCRIPTS_DIR}/k8s-grafana.sh ${MASTER_IP} 
                        fi

                        if [ "${DEPLOY_PROMETHEUS}" == "true" ]; then
                            /bin/bash ${SCRIPTS_DIR}/k8s-prometheus.sh ${DOMAIN_NAME} 
                        fi
                    fi
                SHELL
        end
    end
end